sudo: required
services:
  - docker

before_install:
  - docker build -t jdgronewold/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run -e CI=true jdgronewold/react-test npm test -- --watchAll=false

after_success:
  - docker build -t jdgronewold/vantinerary-client ./client
  - docker build -t jdgronewold/vantinerary-nginx ./nginx
  - docker build -t jdgronewold/vantinerary-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jdgronewold/vantinerary-client
  - docker push jdgronewold/vantinerary-nginx
  - docker push jdgronewold/vantinerary-server

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: vantinerary
#   env: Vantinerary-env
#   bucket_name: elasticbeanstalk-us-west-1-306476627547
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
